### PR TITLE
updates endpoints

### PR DESCRIPTION
**Pull request by ghost**
changes endpoints so that the students can make use of the Express `.Router()` which we demo during the introduction lecture to Express and this exercise.

### CODE REVIEW

**Comment by ghost** [comment]
not sure if this is still needed or whatttttt. Either merge or close! 🙇

**Comment by jaywon** [comment]
@taesup can you see if this is still needed?

**Comment by taesup** [comment]
This actually follow REST more but there are references to the routes where the pluralization is not updated. So yes, still needed but also still needs more work. @jaywon

**Comment by taesup** [comment]
Pulled this work into the Buzzword rewrite PR. Closing this PR since it's no longer relevant.

**Pull request closed without merging**
